Update artifactory test version
Fixing this problem by updating the version on the tests.
```
  1) Library#artifactory_helper #get_delivery_artifact works only with Chef VPN returns artifact of an specific version
     Failure/Error:
       expect(get_delivery_artifact(node, '0.3.607'))
         .to eql(mock_delivery_artifact_for_v_0_3_607)

     NoMethodError:
       undefined method `uri' for nil:NilClass
     # ./libraries/artifactory_helper.rb:95:in `get_delivery_artifact'
     # ./spec/unit/libraries/arfitactory_helper_spec.rb:74:in `block (4 levels) in <top (required)>'
```