Assemble Gem dependencies on a `cache` directory
As a Developer I would expect that the pipeline assemble the Gem
dependencies with out failing so I can push my code without dealing with
problems before even testing my actual change.

**Problem Description**

The current pipeline assemble the Gem dependencies using the ones that
comes with `chefdk` and as they are own by `root` we fail with the
following error:

```
Install rubygem dependencies locally

Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
error: cannot open .git/FETCH_HEAD: Permission denied

Retrying git fetch --force --quiet --tags
"/var/opt/delivery/workspace/delivery.chef.co/chef/delivery/delivery-cluster/clean_aws/acceptance/provision/cache/.bundler/cache/git/chef-provisioning-f503c00e7f835c509b3baff53bec23eb4b7f1ad8"
due to error (2/4): Bundler::Source::Git::GitCommandError Git error:
command `git fetch --force --quiet --tags
"/var/opt/delivery/workspace/delivery.chef.co/chef/delivery/delivery-cluster/clean_aws/acceptance/provision/cache/.bundler/cache/git/chef-provisioning-f503c00e7f835c509b3baff53bec23eb4b7f1ad8"`
in directory
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/bundler/gems/chef-provisioning-ac770060c77e
has failed.
If this error persists you could try removing the cache directory
'/var/opt/delivery/workspace/delivery.chef.co/chef/delivery/delivery-cluster/clean_aws/acceptance/provision/cache/.bundler/cache/git/chef-provisioning-f503c00e7f835c509b3baff53bec23eb4b7f1ad8'
error: cannot open .git/FETCH_HEAD: Permission denied

Retrying git fetch --force --quiet --tags
"/var/opt/delivery/workspace/delivery.chef.co/chef/delivery/delivery-cluster/clean_aws/acceptance/provision/cache/.bundler/cache/git/chef-provisioning-f503c00e7f835c509b3baff53bec23eb4b7f1ad8"
due to error (3/4): Bundler::Source::Git::GitCommandError Git error:
command `git fetch --force --quiet --tags
"/var/opt/delivery/workspace/delivery.chef.co/chef/delivery/delivery-cluster/clean_aws/acceptance/provision/cache/.bundler/cache/git/chef-provisioning-f503c00e7f835c509b3baff53bec23eb4b7f1ad8"`
in directory
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/bundler/gems/chef-provisioning-ac770060c77e
has failed.
If this error persists you could try removing the cache directory
'/var/opt/delivery/workspace/delivery.chef.co/chef/delivery/delivery-cluster/clean_aws/acceptance/provision/cache/.bundler/cache/git/chef-provisioning-f503c00e7f835c509b3baff53bec23eb4b7f1ad8'
error: cannot open .git/FETCH_HEAD: Permission denied
```

**Proposal Solution**

Assemble the Gem dependencies on our local `cache` directory like:
```
bundle install --path $CACHE/.chefdk
````

Close https://github.com/opscode-cookbooks/delivery-cluster/issues/155